config/routes.rb
Rails.application.routes.draw do
  resources :pages, only: [:index]  do
    post :result
  end
  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: %i[ show edit update destroy ]
  
  # GET /pages or /pages.json
  def index
    @page = Page.new
    @page.request = 1
  end

  def result
    
  end
  private
    # Use callbacks to share common setup or constraints between actions.
      
    def set_page
      @page = Page.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def page_params  
      params.require(:page).permit(:question).to_h  
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy, :reset_password, :activate_account, 
                                  :deactivate_account, :unlock_account, :update_password]

	def index
		@users = User.all
	end


	def new
		@user = User.new
	end

	def edit

	end
		
	def update
		if @user.update(user_params)
			flash[:notice] = "Your account information was successfully updated"
			redirect_to @user
		else
			render 'edit'
		end
	end

	def create
		@user = User.new(user_params)
    	@user.password = User::DEFAULT_PASSWORD
    	@user.account_status = 0
		@user.username = @user.last_name + @user.first_name[0,1]
		if @user.save
			flash[:notice] = "User #{@user.username}, has succesfully been made"
			redirect_to users_path
		else
			render 'new'
		end
	end

	def destroy
		@user.destroy
		session[:user_id] = nil if @user == current_user
		flash[:notice] = "Account has been succesfully deleted"
		if @user != current_user
			redirect_to users_path
		else
			redirect_to root_path
		end
	end

	def update_password
    if params[:user].present? 
      if @user.update(user_params)
        @user.update(password_reset: false, password_updated: true)
        bypass_sign_in(@user)
        redirect_to root_url, notice: "Password updated successfully"
      end
    end
  end

  def reset_password
    @user.update(password: User::DEFAULT_PASSWORD, password_reset: true)
    flash[:notice] = "Password reset"
    redirect_to users_path
  end

  def activate_account
    @user.activate
    @user.update(password: User::DEFAULT_PASSWORD, password_update_required: true)
    send_credentials(@user)
    respond_to do |format|
      format.html { redirect_to users_path, success: "User's account was activated, they may now sign in" }
      format.json { head :no_content }
    end
  end

  def deactivate_account
    @user.deactivate
    respond_to do |format|
      format.html { redirect_to users_path, alert: "User's account was deactivated, they may now can no longer have access to the system" }
      format.json { head :no_content }
    end
  end

  def unlock_account
    @user.unlock_access!
    @user.update(password: User::DEFAULT_PASSWORD)
    redirect_to users_path, success: "User's account was successfully unlocked, they may now sign in"
  end
	private
	def user_params
		params.require(:user).permit(:first_name, :middle_name, :last_name, :username, :email, :role, :password)
	end

	def set_user
		@user  = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def full_name(user)
		"#{user.first_name} #{user.last_name}"		
	end

	def editor?
		current_user and current_user.editor?
	end

	def admin?
		current_user and current_user.admin?
	end

	def only_admins
		redirect_to root_path, alert: @not_allowed_message if !admin? 
	end

	def only_admins_or_editors
		 redirect_to root_path, alert: @not_allowed_message if !admin? and !editor?
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer footer-transparent mt-auto d-print-none">
  <div class="container">
      <div class="col-12 col-lg-auto mt-3 mt-lg-0">
        <ul class="list-inline list-inline-dots mb-0">
          <li class="list-inline-item">
            Copyright © <%= DateTime.now.year %>
            Doron W. Cassell
            All rights reserved.
          </li>
          <li class="list-inline-item">
            <a href="" class="link-secondary" rel="noopener">Beta v1.0</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-expand-md navbar-dark d-print-none">
  <div class="container-xl">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-menu">
      <span class="navbar-toggler-icon"></span>
    </button>
    <h1 class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-0 pe-md-3">
      <%= link_to "Chat Bot", root_path, class: "text-decoration-none" %>
    </h1>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat Bot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://unpkg.com/@tabler/core@1.0.0-beta9/dist/js/tabler.min.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/@tabler/core@1.0.0-beta9/dist/css/tabler.min.css">
  </head>

  <body class="d-flex flex-column h-100">
    <%= render 'layouts/navigation' %>
    <div class="page-wrapper">
      <div class="container-xl">
        <div class="page-body">
          <%= render 'layouts/messages' %> 
          <%= yield %>
        </div>
      </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/_form.html.erb
<%=  form_for :location, :url=>page_result_path(@page.request) do |f| %>
  <div class="input-group">
    <button type="button" id="speak" class=" btn btn-pill btn-icon btn-info">
      <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-microphone" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
         <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
         <rect x="9" y="2" width="6" height="11" rx="3"></rect>
         <path d="M5 10a7 7 0 0 0 14 0"></path>
         <line x1="8" y1="21" x2="16" y2="21"></line>
         <line x1="12" y1="17" x2="12" y2="21"></line>
      </svg>
    </button>
    <%=  f.text_field '', id:'request', class:'form-control' %>
    </div>
  
<% end %>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container-xl">
  <div class="row">
    <div class="col-6">
      <%= render 'form' %>
      <p class="text-muted text-center m-1">Start chatbot interactions by clicking the button with the mic or typing into the chatbox</p>
    </div>
    <div class="col-6">
      <div class="card mb-2">
        <div class="ribbon ribbon-top bg-info">
          <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-info-circle" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
           <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
           <circle cx="12" cy="12" r="9"></circle>
           <line x1="12" y1="8" x2="12.01" y2="8"></line>
           <polyline points="11 12 12 12 12 16 13 16"></polyline>
          </svg>
        </div>
        <div class="card-body">
          <h3 class="card-title text-primary">Chatbot Evaluation Form</h3>
          <p class="text-muted">
            My name is Doron Cassell a third year Computer Science Double Major student at the University of the West Indies Cave Hill Campus. The following questionnaire will help me evaluate the chatbot created for my research project.
          </p>
          <a href="https://docs.google.com/forms/d/e/1FAIpQLScOz54y0emejxk2NQgwTszDEHMFW8WLd-4zHEP2KNWZlJUQtg/viewform?usp=sf_link" class="btn btn-pill bg-info">
            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-file-text" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
               <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
               <path d="M14 3v4a1 1 0 0 0 1 1h4"></path>
               <path d="M17 21h-10a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2h7l5 5v11a2 2 0 0 1 -2 2z"></path>
               <line x1="9" y1="9" x2="10" y2="9"></line>
               <line x1="9" y1="13" x2="15" y2="13"></line>
               <line x1="9" y1="17" x2="15" y2="17"></line>
            </svg>
            Form
          </a>
        </div>
      </div>
      <div class="card">
        <div class="ribbon ribbon-top bg-primary">
          <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-help" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
            <circle cx="12" cy="12" r="9"></circle>
            <line x1="12" y1="17" x2="12" y2="17.01"></line>
            <path d="M12 13.5a1.5 1.5 0 0 1 1 -1.5a2.6 2.6 0 1 0 -3 -4"></path>
          </svg>
        </div>
        <div class="card-body">
          <h3 class="card-title text-primary">User Tips</h3>
          <p class="text-muted">
            <b>Start by saying hello or asking any of the below questions.</b><br>
            Examples:<br>
            What is covid-19?<br>
            How do I protect myself against covid-19?<br>
            Why do I need the covid-19 vaccine?<br>
            What vaccines are available to counter covid-19?<br>
            Who should take the covid-19 vaccine?<br>
            Who should not take the covid-19 vaccine?<br>
            Where can I get vaccinated?<br>
            What are the side effects of the covid-19 vaccines?<br>
            When am I fully vaccinated?<br>
            How long does the vaccine protect me against covid-19?<br>
            What are the symptoms of covid-19?<br>
            Where can I get tested for covid-19?<br>
            What do I do if I have covid-19?<br>
            How is the coronavirus spread?<br>
            How long does covid-19 stay in your system?<br>
            How many covid-19 cases are there in Barbados?            
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class="alert alert-danger alert-dismissible fade show" role="alert">
		<h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %>  from being saved</h4>
		<ul>
			<% obj.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>
<% end %>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  
  <%= render 'shared/errors', obj: @user %>
  <div class="form-inputs">

    <div class="mb-3">
      <%= f.input :first_name, :label_html => { class: "form-label" }, :input_html => { placeholder: "Enter first name" } %>
    </div>

    <div class="mb-3">
      <%= f.input :middle_name, :label_html => { class: "form-label" }, :input_html => { placeholder: "Enter middle name" } %>
    </div>

    <div class="mb-3">
      <%= f.input :last_name, :label_html => { class: "form-label" }, :input_html => { placeholder: "Enter last name" } %>
    </div>

    <div class="mb-4">
      <%= f.input :email, :label_html => { class: "form-label" }, :input_html => { placeholder: "Enter email address" } %>
    </div>
      <h3>User privileges</h3>
      <div class="mb-3">
        <%= f.input :role, :prompt     => "Please select a user role", :label_html => { class: "form-label" }, :collection => User::roles.values %>
      </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
  
<h1>Editing User</h1>

<%= render 'form', user: @user %>
<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="col-12">
  <div class="card">
    <div class="table-responsive">
      <table class="table table-vcenter table-mobile-md card-table">
        <thead>
          <tr>
            <th>User</th>
            <th>Role</th>
            <th>Account Status</th>
            <th>Username</th>
            <th>Last Signed In</th>
            <th class="w-1"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>  
              <td data-label="Name">
                <div class="d-flex py-1 align-items-center">
                  <div class="flex-fill">
                    <div class="font-weight-medium"><%= full_name(user) %></div>
                    <div class="text-muted"><a href="#" class="text-reset"><%= user.email %></a></div>
                  </div>
                </div>
              </td>

              <td class="text-muted" data-label="Role"><%= User.roles[user.role] %></td>
              <td><%= user.account_status.capitalize%></td>
              <td><%= user.username %></td>
              <td><%= user.last_sign_in_at %></td>
              
              <td>
                <div class="btn-list flex-nowrap">
                  <%= link_to "Edit", edit_user_path(user), class: "btn btn-white" %>
                  <%= link_to 'Reset Password', reset_password_user_path(user), class: "btn btn-primary", action: :reset_password, 
                    data: { confirm: "Are you sure you want to reset this user's password?" } %>                
                  
                 
                  <%# if (admin? or super_admin?) and user.locked_at != nil %>
                    <%# link_to "Unlock", unlock_account_user_path(user), class: "btn btn-primary", action: :unlock_account, :method => :patch,
                      data: { confirm: "Are you sure you want to unlock this account?" } %>
                  <%# end %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>  

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>
<%= link_to 'Back', users_path %>

app/views/users/update_password.html.erb
<div class="flex-fill d-flex flex-column justify-content-center py-4">
  <div class="container-tight py-6">
    <div class="text-center mb-4">
      <!-- <a href="."><img src="./static/logo.svg" height="36" alt=""></a> -->
    </div>

    <%= simple_form_for(@user, url: { :action => "update_password" }, method: :post, html: {class: "card card-md" }) do |f| %>
      <%= f.error_notification %>
      
      <div class="card-body">
        <h2 class="card-title text-center mb-4">Change your password</h2>
        <div class="mb-3">
          <%= f.input :password,
                      required: true,
                      label_html: { class: "form-label" },
                      input_html: { autocomplete: "new-password" } %>
        </div>
        <div class="form-footer">
          <%= f.button :button, "Update", class: "btn btn-primary w-100", 
                       :data => { disable_with: "<div class="'spinner-border'" role="'status'"></div>"} %>
        </div>
      </div>
    <% end %>
  </div>
</div>